swagger: "2.0"
info:
  description: "Holidays Webhook の API です。"
  version: "0.1.1"
  title: "Holidays Webhook API"
  contact:
    email: "info@ambitiuos-i.net"
servers:
  - url: 'https://holidays-webhook.ambitious-i.net/'
    description: Production
  - url: 'http://localhost:8000'
    description: Local
paths:

  /:
    get:
      summary: "index"
      description: "現在時刻を返す（DB 側とサーバー側）"
      responses:
        200:
          description: "レスポンス"
          content:
            application/json:
              schema:
                type: object
                properties:
                  server:
                    type: string
                    format: date-time
                    example: 2021-09-05 08:27:23 UTC
                    description: サーバー側の現在時刻
                  db:
                    type: string
                    format: date-time
                    example: 2021-09-05 17:27:23
                    description: DB 側の現在時刻
  /holiday/cache/clear:
    get:
      summary: "cache clear"
      description: "祝日のキャッシュをクリアする"
      responses:
        200:
          description: "レスポンス"
          content:
            application/json:
              schema:
                type: object
                properties:
                  holidays:
                    type: array
                    description: 祝日データ（クリアしているため空）
