CREATE TABLE groups
(
    id INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
    uid VARCHAR(256) NOT NULL COMMENT 'Google UID',
    email VARCHAR(512) NOT NULL COMMENT 'EMail',
    premium TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'プラミアムフラグ',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted DATETIME COMMENT '削除日時',
    PRIMARY KEY (id)
) COMMENT 'グループ（家族）情報';